### ISSUE TITLE
Rails 5.0 대응

### ISSUE THREAD

**Issue by riseshia** [rorlakr/rails-guides#46]
본가 WIP는 일단 제외합니다.
[현재 미번역된 페이지도 WIP에 포함되어 있음]
- [x] Upgrade guide(#42)
- [x] 5.0 Release note(#44)
- [x] Active Model Basics(#51)
- [x] The Rails Command Line(#50)
- [x] Action Cable Overview(#48)
- [x] Caching with Rails: An Overview(#53)
- [x] Testing Rails Applications(#55)
- [x] Using Rails for API-only Applications(#54)

**Comment by riseshia** [comment]
Done XD
